### ISSUE TITLE
Plot - change axis limits

### ISSUE THREAD

**Issue by martinhulenyi** [synth-inference/synthdid#110]
Maybe a stupid question but is there a way I can change the axis limits of the produces synthdid plot?

**Comment by davidahirshberg** [comment]
It's a ggplot.  Say '+ xlim(lower, upper)' or '+ ylim(lower, upper)'

**Comment by martinhulenyi** [comment]
Thank you very much! 
A supplementary question - for the ggplot, can I remove the plot of the time weights and the did effect?
