### ISSUE TITLE
Replication code for Table 1

### ISSUE THREAD

**Issue by elizabeth-richardson** [synth-inference/synthdid#111]
Thanks for a great paper and package. I've found the replication code for the simulations, but would like to also see the code for the cigarette tax results that you've reported in table 1. Is this available?

**Comment by davidahirshberg** [comment]
It is! Take a look here: https://synth-inference.github.io/synthdid

**Comment by davidahirshberg** [comment]
Yes for SC and DID. We don't include the Matrix Completion or DIFP
estimators there.

Keep in mind that while we report a standard error for these things,
they're based on very strong assumptions. There's just not much you can do
without them when you have only one treated unit.

**Comment by davidahirshberg** [comment]
And our package is giving us these standard errors for the SC and DID
estimates.

**Comment by elizabeth-richardson** [comment]
Ah! I see. Very helpful. Thanks for your help.
