### ISSUE TITLE
What are the treatment effect +- numbers? 

### ISSUE THREAD

**Issue by JAFHall** [synth-inference/synthdid#124]
For instance, when I print my treatment estimate, I get something like 

> synthdid: 2.575 +- 0.886

I thought this was a confidence interval, but am somewhat perplexed.

**Comment by davidahirshberg** [comment]
You got it.  It's a 95% interval: (point estimate) +- 1.96 * (estimated standard error).

See the [format method](https://github.com/davidahirshberg/synthdid/blob/7468c1a04b2716a4fbcbc8f40bb83a182ca0737a/R/format.R#L9) for more details on what's printed.

**Comment by JAFHall** [comment]
Thanks for confirming!
