### ISSUE TITLE
`Y.beta` contraction after updating `grad.beta`

### ISSUE THREAD

**Issue by TheFightMilk** [synth-inference/synthdid#23]
Shouldn't this be `Y.beta = Y - contract3(X,beta)`? 

https://github.com/synth-inference/synthdid/blob/f71035b415299c6bb49e29b27f0ab3c44cb3b1c0/R/synthdid.R#L115

**Comment by davidahirshberg** [comment]
Yes. There were complementary sign errors that made it fit correctly if you were going to use beta like Y.beta = Y + contract3(X,beta) after fitting.  But we weren't doing that. 

I've fixed this and added [one test](https://github.com/synth-inference/synthdid/blob/fd66c8f55da9fb34ba2d550c73ee2e673c117092/tests/testthat/test_synthdid.R#L42). If you have test cases you'd like added, please submit a PR. It would be great to have better test coverage.

Thanks for bringing this to our attention.

**Comment by TheFightMilk** [comment]
Thanks for the clarification. I will submit a PR with some test cases soon.
