### ISSUE TITLE
Build is Broken?

### ISSUE THREAD

**Issue by rawls238** [synth-inference/synthdid#26]
On Mac OS X version 10.15.6, R version 4.0.2 I run into the following error when trying to install according to the provided instructions:

```
Error : (converted from warning) /private/var/folders/34/4z3y84xd4t30hk393dnhg8wr0000gn/T/Rtmpw36Iaq/R.INSTALLaf1169d96c9a/synthdid/man/synthdid_units_plot.Rd:20: unknown macro '\item'
ERROR: installing Rd objects failed for package ‘synthdid’
```

**Comment by davidahirshberg** [comment]
Try again.  It looks like the build broke because an autogenerated doc file had some kind of syntax error. 
For now, I've removed the doc file, and it's installing for me.

**Comment by rawls238** [comment]
works now! thanks for the fast response
