### ISSUE TITLE
error:Ignoring unknown aesthetics: frame

### ISSUE THREAD

**Issue by zdlspace0528** [synth-inference/synthdid#51]
> plot(tau.hat)
Ignoring unknown aesthetics: frameIgnoring unknown aesthetics: frameIgnoring unknown aesthetics: frameIgnoring unknown aesthetics: frameIgnoring unknown aesthetics: frameIgnoring unknown aesthetics: frame`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.

How can i solve this problem?

Raymond

**Comment by davidahirshberg** [comment]
This is just a warning, correct? Is everything plotting as you'd like?

It's a little hard to get rid of the 'unknown aesthetics: frame' warning outright because some ways of displaying the plot (e.g. ggplotly) use it and some don't and complain about it.

**Comment by davidahirshberg** [comment]
What you're describing shouldn't warn in the new version of the package. Let us know if it does.

**Comment by zdlspace0528** [comment]
Now it gets a warning ,


> plot(tau.hat, se.method='placebo')
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.


Best
Raymond


| |
zdlspace
|
|
***@***.***
|
签名由网易邮箱大师定制


On 03/14/2021 ***@***.***> wrote：

What you're describing shouldn't warn in the new version of the package. Let us know if it does.

**Comment by davidahirshberg** [comment]
Thanks. Give it another shot,
