### ISSUE TITLE
devtools::load_all error

### ISSUE THREAD

**Issue by davidahirshberg** [synth-inference/synthdid#53]
From an R session in the directory including the README:

> 

devtools::load_all('.')
Loading synthdid
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'setup.R': No such file or director

Is there a missing file?

**Comment by erikcs** [comment]
This runs fine here:
![Screen Shot 2021-03-10 at 20 11 43](https://user-images.githubusercontent.com/7185264/110734550-e5048900-81dc-11eb-883c-2889d40a6c5f.png)

**Comment by davidahirshberg** [comment]
I see. This runs fine in a clean repo but seems to break as a result of non-package files.  Maybe not the solution we're looking for.
