### ISSUE TITLE
How to calculate se using bootstrap method

### ISSUE THREAD

**Issue by jaderjuca** [synth-inference/synthdid#89]
When I run `se = sqrt(vcov(tau.hat, method='bootstrap'))` i get NA, the only method that seems to work is the 'placebo'.

I also tried the following:
`vcov.synthdid_estimate(tau.hat,method = "bootstrap", replications = 200)`

**Comment by davidahirshberg** [comment]
How many treated units do you have?

**Comment by jaderjuca** [comment]
I made a mistake while coding and was using only 1 treated. Now it's working properly with 3 treated units.
Thanks for the reply and sorry for the inconvenience.
