### ISSUE TITLE
Minor documentation issues

### ISSUE THREAD

**Issue by karldw** [synth-inference/synthdid#9]
I'm interested in using SDID in one of my current projects. I really appreciate you all providing the implementation in an R package!

I saw @davidahirshberg [mentioned](https://github.com/synth-inference/synthdid/commit/68ccb22522ba949bc0fd86d94ddfc48ae36d21d3) issues with the OSQP and SCS solvers. is your recommendation to use always use ECOS for SDID estimation?

I ran `devtools::check()` on the package and noticed a few places it was unhappy with the documentation or packaging. Would it be helpful if I submitted a pull request for these issues?
If so, do you want to add a [license](https://choosealicense.com/) to the package?

Thanks!

**Comment by davidahirshberg** [comment]
Yes, use ECOS. If you're just getting started, I'd recommend using my fork:
https://github.com/davidahirshberg/synthdid. We'll be updating the
synth-inference repo from it soon. Solver options other than ECOS have been
removed.

It's not a great time for a PR. Thanks for offering.

**Comment by karldw** [comment]
Sounds great, thanks!
